# HTTP Server
server:
  port: ${PORT:3333}   # HTTP port

# Spring properties
spring:
  application:
    name: sadr-service

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'